---
substitutions:
  primary_thermostat_address: "0x380"

text_sensor:
  - platform: econet
    id: zone${zonenumber}_equipment_name
    name: Zone${zonenumber} Equipment Name
    src_address: ${zone_thermostat_address}
    sensor_datapoint: EQP_NAME
    request_mod: ${zone_thermostat_requestmod}
    entity_category: "diagnostic"
    request_once: true

climate:
  - platform: econet
    id: zone${zonenumber}_climate
    name: ${zonename} Climate
    request_mod: ${zone_thermostat_requestmod}
    src_address: ${zone_thermostat_address}
    visual:
      min_temperature: "50 °F"
      max_temperature: "90 °F"
      temperature_step:
        target_temperature: "0.5 °F"
        current_temperature: "0.1 °F"
    current_temperature_datapoint: SPT
    target_temperature_low_datapoint: HEATSETP
    target_temperature_high_datapoint: COOLSETP
    mode_datapoint: STATMODE
    modes:
      0: "HEAT"
      1: "COOL"
      2: "HEAT_COOL"
      3: "FAN_ONLY"
      4: "OFF"
    custom_fan_mode_datapoint: STAT_FAN
    custom_fan_mode_no_schedule_datapoint: STATNFAN
    follow_schedule_datapoint: SCHEDULE
    custom_fan_modes:
      0: "Automatic"
      1: "Speed 1 (Low)"
      2: "Speed 2 (Medium Low)"
      3: "Speed 3 (Medium)"
      4: "Speed 4 (Medium High)"
      5: "Speed 5 (High)"
    current_humidity_datapoint: RELH7005
    target_dehumidification_level_datapoint: DHUMSETP


sensor:
  - platform: econet
    src_address: ${zone_thermostat_address}
    id: zone${zonenumber}_temperature
    name: ${zonename} Temperature
    sensor_datapoint: SPT
    request_mod: none
    device_class: temperature
    unit_of_measurement: "°F"
    state_class: measurement
    filters:
      - delta: 0.1

  - platform: econet
    src_address: ${zone_thermostat_address}
    id: zone${zonenumber}_humidity
    name: ${zonename} Humidity
    sensor_datapoint: RELH7005
    request_mod: none
    unit_of_measurement: "%"
    accuracy_decimals: 1
    device_class: humidity
    state_class: measurement
    filters:
      - delta: 0.3

  - platform: econet
    src_address: ${primary_thermostat_address}
    id: zone${zonenumber}_cfm
    name: ${zonename} CFM
    sensor_datapoint: Z${zonenumber}CFMDSP
    request_mod: ${primary_thermostat_requestmod}
    state_class: "measurement"
    entity_category: "diagnostic"
    unit_of_measurement: "cfm"

